### ISSUE TITLE
Spinning Circle in Plex App for iOS

### ISSUE THREAD

**Issue by bryannorton** [41john/NFL.bundle#5]
When using the Plex App for iOS on either an iPhone or iPad, live streams will play, but are dark and have the spinning loading circle constantly running as shown in the attached screen shot.  This might just need a "duration" statement in the init.py file.
![img_8717](https://cloud.githubusercontent.com/assets/21001528/20195267/74813878-a75b-11e6-9ac6-7dad1f234da4.PNG)

**Comment by 41john** [comment]
Have you been able to try this with success? I had a quick look at it but it didn't seem to make any difference.

**Comment by bryannorton** [comment]
Not really.  From what I could tell, since it gives you the option of choosing your stream quality, it ignores the duration element if you put it in there.  But I don't know nearly enough about how to get around that.
