### ISSUE TITLE
Streaming quality low?

### ISSUE THREAD

**Issue by ChriD** [41john/NFL.bundle#9]
Hi, 
Is there an issue with the streaming quality?
It says its streaming with 4.5Mbps at 720p HD but it looks like 640x480
If i start the stream from the nfl site its much better.

**Comment by jjoles** [comment]
This is happening to me as well.  :\

**Comment by cbmartinx** [comment]
Sadly still happening to me too. Otherwise works great.

**Comment by magu** [comment]
I think this is a client issue. It did this to me in web client but works fine in iOS/tvOS/PS4/Mac Plex clients.

**Comment by cbmartinx** [comment]
I'm seeing only the low resolution version on the web, Android, Xbox and Roku clients. iOS client won't load the video at all for some reason. Don't have Windows or Mac clients to test.

**Comment by ChriD** [comment]
i have low resolution on rasplex.
